name: 'Create GitHub Release'
description: 'Creates a GitHub release with installation instructions'

inputs:
  tag:
    description: 'The git tag for the release'
    required: true
  version:
    description: 'The version number'
    required: true
  repository:
    description: 'The GitHub repository (owner/name)'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ inputs.tag }}
        name: Release ${{ inputs.version }}
        body: |
          ## Installation

          To use this version in your Go project, run:

          ```bash
          go get github.com/${{ inputs.repository }}@${{ inputs.tag }}
          ```

          Or add it to your `go.mod`:

          ```go
          require github.com/${{ inputs.repository }} ${{ inputs.tag }}
          ```
        generateReleaseNotes: true
        draft: false
        prerelease: false
