name: CI

on:
  push:
    branches: [ main, bugfix/* ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Go env
        run: |
          go env
          go version

      - name: Enable Docker (for testcontainers)
        uses: docker/setup-buildx-action@v3

      - name: Run Tests (including postgres)
        env:
          CGO_ENABLED: 1
        run: |
          go generate ./...
          go test ./pkg/... ./internal/... --tags=postgres

  verify-examples:
    name: Run example ${{ matrix.example }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        example:
          - sync-pull-dataplane
          - streaming-pull-dataplane
          - streaming-push-dataplane
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Go env
        run: |
          go env
          go version

      - name: Run example
        working-directory: examples/${{ matrix.example }}
        run: |
          go build .
          go run .
    
     
